name: BuildAndRunTests

on:
  [push, pull_request]

jobs:
  build_and_run_tests:
    name: Build and run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-13', 'windows-latest']
        build-with: ['headers', 'modules']
        exclude:
          - os: macos-13
            build-with: modules
          - os: ubuntu-latest
            build-with: modules
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Setup XCode # TODO remove this when xcode 15 will be default on github actions
      uses: maxim-lobanov/setup-xcode@v1 
      if: runner.os == 'macOS'
      with:
        xcode-version: '15.0'
    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install cmake ninja-build libtbb-dev
    - name: Install dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install cmake ninja
    - name: Install dependencies
      if: runner.os == 'Windows'
      run: |
        choco upgrade ccache ninja
    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-${{ matrix.build-with }}-${{ github.ref }}
    - name: Build (headers)
      if: matrix.build-with == 'headers'
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Release ..
        ninja
    - name: Build (modules)
      if: matrix.build-with == 'modules'
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -GNinja -DVCLIB_BUILD_CXX20_MODULES=ON -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Release ..
        ninja
    - name: Run Tests
      shell: bash
      run: |
        cd build
        ctest --verbose
