name: BuildAndRunTests

on:
  [push, pull_request]

jobs:
  meshlab_build:
    name: Build and run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-13', 'windows-latest']
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: "14.36" # TODO remove this config when will be default on github actions
    - uses: maxim-lobanov/setup-xcode@v1 # TODO remove this when xcode 15 will be default on github actions
      if: runner.os == 'macOS'
      with:
        xcode-version: '15.0-beta'
    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install cmake ninja-build libtbb-dev
    - name: Install dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install cmake ninja
    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-${{ github.ref }}
    - name: Build
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
        ninja
    - name: Run Tests
      shell: bash
      run: |
        cd build
        ctest --verbose