name: BuildAndRunTests

on:
  [push, pull_request]

jobs:
  meshlab_build:
    name: Build and run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: "14.36" # TODO remove this config when will be default on github actions
    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install cmake ninja-build libtbb-dev
    - name: Install dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install cmake ninja llvm # TODO remove llvm when clang 16 will be default on macos runners
    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-${{ github.ref }}
    - name: Build
      if: runner.os != 'macOS' # TODO remove this when clang 16 will be default on macos runners
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
        ninja
    - name: Build MacOS # TODO remove this when clang 16 will be default on macos runners
      if: runner.os == 'macOS'
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ -GNinja -DCMAKE_BUILD_TYPE=Release ..
        ninja
    - name: Run Tests
      shell: bash
      run: |
        cd build
        ctest --verbose