name: Render - Emscripten Build

on:
  [push, pull_request]

jobs:
  render_emscripten_build:
    name: Render - Emscripten Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt-get install cmake ninja-build libtbb-dev libx11-dev libgl1-mesa-dev
    - name: Setup Emscripten SDK
      uses: emscripten-core/setup-emsdk@v16
    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2.22
      with:
        key: render-emscripten-ubuntu-latest-${{ github.ref_name }}
    - name: Build
      shell: bash
      run: |
        mkdir build
        cmake -B build --preset=vclib-render-bgfx-emscripten-release \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build build --parallel
