name: Run clang-format Linter

# run it every day at midnight, or manually
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run_clang_format_linter:
    if: github.repository == 'cnr-isti-vclab/vclib'
    name: Run clang-format Linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        exclude: './external ./scripts'
        extensions: 'h,cpp'
        clangFormatVersion: 16
        inplace: True
    - uses: EndBug/add-and-commit@v9
      with:
        committer_name: GitHub Actions
        committer_email: actions@github.com
        message: '[clang-format] Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}